---

- name: 'Install additional packages'
  become: true
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop:
    - sysstat
    - acpi #only for laptops


- name: 'Create i3 config'
  copy:
    src: i3-config
    dest: ~/.config/i3/config
    mode: '0660'

- name: 'Create lxterminal config'
  copy:
    src: lxterminal-config
    dest: ~/.config/lxterminal/lxterminal.conf
    mode: '0660'

- name: 'Create tmux config'
  copy:
    src: tmux-config
    dest: ~/.tmux.conf
    mode: '0660'

- name: 'Install status bar'
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - psutil
    - netifaces
    - bumblebee-status
