# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: yokogawa/ansible-lint
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_cachink: true
      - run: find . -name "*.yml" | grep -v mails.yml | grep -v hosts.yml | xargs -r ansible-lint --force-color
