---

- name: 'Include hosts information'
  include_vars:
    file: hosts.yml

- name: 'Insert hosts to config file'
  blockinfile:
    dest: ~/.ssh/config
    block: "{{ lookup('template', 'config.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ item.host }}"
    create: yes
    mode: 0644
  with_items: "{{ ssh_hosts }}"
