---

- name: 'Clone doom repository'
  git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: '~/.emacs.d'
    version: 'c4fc1587fee64fcba48c0f0b6158d69ed63992c3'

- name: 'Install doom'
  script: ~/.emacs.d/bin/doom -y install

- name: 'Copy doom scripts'
  copy:
    src: doom/"{{ item }}"
    dest: ~/.doom.d/"{{ item }}"
    mode: '0644'
  loop:
    - config.el
    - init.el
    - packages.el
