---

- name: 'Install emacs package'
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
    - emacs
    - git
    - ca-certificates
  become: yes

- name: 'Install emacs mu4e packages'
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
      - isync
      - mu4e
  become: yes

- name: 'Install spacemacs'
  include: spacemacs.yml
  tags: spacemacs

- name: 'Install doom emacs'
  include: doom_emacs.yml
  tags: doom_emacs
