---

- name: 'Install emacs package'
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
    - emacs
    - git
    - ca-certificates
  become: yes

- name: 'Install emacs mu4e packages'
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no
  vars:
    packages:
      - isync
      - mu4e
  become: yes
